// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;

namespace TestFramework.Tooling.UnitTestLauncher.Tests
{
    /// <summary>
    /// This is a program that tests the non-generated code of the
    /// TestFramework.Tooling.UnitTestLauncherGenerator This project
    /// can also be used to code and debug that code.
    ///
    /// The code is included in the TestFramework.Tooling as embedded resource.
    /// It is not tested in the build of TestFramework.Tooling.
    ///
    /// The code below the line depends on the TestFramework.Tooling.Tests.Execution.v3
    /// project. Check and run the test TestFramework_Tooling_UnitTestLauncher_Tests_Asserts
    /// in TestFramework.Tooling.Tests to verify that the data is still correct.
    /// </summary>
    public class Program
    {
        public static void Main()
        {
            Console.WriteLine("========================================");
            Console.WriteLine("UnitTestLauncher test program");
            Console.WriteLine("========================================");

            nanoFramework.TestFramework.Tools.UnitTestLauncher.Run("***");
        }
    }
}

//===========================================================================================
//
// The code below is normally generated by the UnitTestLauncherGenerator.
//
// The code may need to be adapted if the TestFramework.Tooling.Tests.Execution.v3
// project is updated.
//
// Check and run the test TestFramework_Tooling_UnitTestLauncher_Tests_Asserts
// in TestFramework.Tooling.Tests to verify that the data is still correct.
//

namespace nanoFramework.TestFramework.Tools
{
    public partial class UnitTestLauncher
    {
        private partial void RunUnitTests()
        {
            ForClass(
                typeof(global::TestFramework.Tooling.Execution.Tests.StaticTestClass), (int)TestClassInitialisation.NoInstantiation,
                nameof(global::TestFramework.Tooling.Execution.Tests.StaticTestClass.Setup), null,
                nameof(global::TestFramework.Tooling.Execution.Tests.StaticTestClass.Cleanup),
                (frm, fdr) =>
                {
                    frm(nameof(global::TestFramework.Tooling.Execution.Tests.StaticTestClass.Method1), null);
                    frm(nameof(global::TestFramework.Tooling.Execution.Tests.StaticTestClass.Method2), null);
                }
            );

            ForClass(
                typeof(global::TestFramework.Tooling.Execution.Tests.StaticTestClassSetupCleanupPerMethod), (int)TestClassInitialisation.SetupCleanupPerTestMethod,
                nameof(global::TestFramework.Tooling.Execution.Tests.StaticTestClassSetupCleanupPerMethod.Setup), null,
                nameof(global::TestFramework.Tooling.Execution.Tests.StaticTestClassSetupCleanupPerMethod.Cleanup),
                (frm, fdr) =>
                {
                    frm(nameof(global::TestFramework.Tooling.Execution.Tests.StaticTestClassSetupCleanupPerMethod.Method1), null);
                    frm(nameof(global::TestFramework.Tooling.Execution.Tests.StaticTestClassSetupCleanupPerMethod.Method2), null);
                }
            );

            ForClass(
                typeof(global::TestFramework.Tooling.Execution.Tests.NonStaticTestClass), (int)TestClassInitialisation.InstantiateForAllMethods,
                nameof(global::TestFramework.Tooling.Execution.Tests.NonStaticTestClass.Setup), null,
                nameof(global::TestFramework.Tooling.Execution.Tests.NonStaticTestClass.Cleanup),
                (frm, fdr) =>
                {
                    frm(nameof(global::TestFramework.Tooling.Execution.Tests.NonStaticTestClass.Method1), null);
                    frm(nameof(global::TestFramework.Tooling.Execution.Tests.NonStaticTestClass.Method2), null);
                }
            );

            ForClass(
                typeof(global::TestFramework.Tooling.Execution.Tests.NonStaticTestClassSetupCleanupPerMethod), (int)(TestClassInitialisation.InstantiateForAllMethods | TestClassInitialisation.SetupCleanupPerTestMethod),
                nameof(global::TestFramework.Tooling.Execution.Tests.NonStaticTestClassSetupCleanupPerMethod.Setup), null,
                nameof(global::TestFramework.Tooling.Execution.Tests.NonStaticTestClassSetupCleanupPerMethod.Cleanup),
                (frm, fdr) =>
                {
                    frm(nameof(global::TestFramework.Tooling.Execution.Tests.NonStaticTestClassSetupCleanupPerMethod.Method1), null);
                    frm(nameof(global::TestFramework.Tooling.Execution.Tests.NonStaticTestClassSetupCleanupPerMethod.Method2), null);
                }
            );

            ForClass(
                typeof(global::TestFramework.Tooling.Execution.Tests.NonStaticTestClassInstancePerMethod), (int)(TestClassInitialisation.InstantiatePerTestMethod | TestClassInitialisation.SetupCleanupPerTestMethod),
                nameof(global::TestFramework.Tooling.Execution.Tests.NonStaticTestClassInstancePerMethod.Setup), null,
                nameof(global::TestFramework.Tooling.Execution.Tests.NonStaticTestClassInstancePerMethod.Cleanup),
                (frm, fdr) =>
                {
                    frm(nameof(global::TestFramework.Tooling.Execution.Tests.NonStaticTestClassInstancePerMethod.Method1), null);
                    frm(nameof(global::TestFramework.Tooling.Execution.Tests.NonStaticTestClassInstancePerMethod.Method2), null);
                }
            );

            ForClass(
                typeof(global::TestFramework.Tooling.Execution.Tests.FailInConstructor), (int)TestClassInitialisation.InstantiateForAllMethods,
                nameof(global::TestFramework.Tooling.Execution.Tests.FailInConstructor.Setup), null,
                nameof(global::TestFramework.Tooling.Execution.Tests.FailInConstructor.Cleanup),
                (frm, fdr) =>
                {
                    frm(nameof(global::TestFramework.Tooling.Execution.Tests.FailInConstructor.Test), null);
                }
            );

            ForClass(
                typeof(global::TestFramework.Tooling.Execution.Tests.FailInSetup), (int)TestClassInitialisation.InstantiateForAllMethods,
                nameof(global::TestFramework.Tooling.Execution.Tests.FailInConstructor.Setup), null,
                nameof(global::TestFramework.Tooling.Execution.Tests.FailInConstructor.Cleanup),
                (frm, fdr) =>
                {
                    frm(nameof(global::TestFramework.Tooling.Execution.Tests.FailInSetup.Test), null);
                }
            );

            ForClass(
                typeof(global::TestFramework.Tooling.Execution.Tests.FailInTest), (int)TestClassInitialisation.InstantiateForAllMethods,
                nameof(global::TestFramework.Tooling.Execution.Tests.FailInConstructor.Setup), null,
                nameof(global::TestFramework.Tooling.Execution.Tests.FailInConstructor.Cleanup),
                (frm, fdr) =>
                {
                    frm(nameof(global::TestFramework.Tooling.Execution.Tests.FailInTest.Test), null);
                }
            );

            ForClass(
                typeof(global::TestFramework.Tooling.Execution.Tests.InconclusiveInTest), (int)TestClassInitialisation.InstantiateForAllMethods,
                nameof(global::TestFramework.Tooling.Execution.Tests.FailInConstructor.Setup), null,
                nameof(global::TestFramework.Tooling.Execution.Tests.FailInConstructor.Cleanup),
                (frm, fdr) =>
                {
                    frm(nameof(global::TestFramework.Tooling.Execution.Tests.InconclusiveInTest.Test), null);
                }
            );

            ForClass(
                typeof(global::TestFramework.Tooling.Execution.Tests.CleanupFailedInTest), (int)TestClassInitialisation.InstantiateForAllMethods,
                nameof(global::TestFramework.Tooling.Execution.Tests.FailInConstructor.Setup), null,
                nameof(global::TestFramework.Tooling.Execution.Tests.FailInConstructor.Cleanup),
                (frm, fdr) =>
                {
                    frm(nameof(global::TestFramework.Tooling.Execution.Tests.CleanupFailedInTest.Test), null);
                }
            );

            ForClass(
                typeof(global::TestFramework.Tooling.Execution.Tests.FailInCleanUp), (int)TestClassInitialisation.InstantiateForAllMethods,
                nameof(global::TestFramework.Tooling.Execution.Tests.FailInConstructor.Setup), null,
                nameof(global::TestFramework.Tooling.Execution.Tests.FailInConstructor.Cleanup),
                (frm, fdr) =>
                {
                    frm(nameof(global::TestFramework.Tooling.Execution.Tests.FailInCleanUp.Test), null);
                }
            );

            ForClass(
                typeof(global::TestFramework.Tooling.Execution.Tests.FailInDispose), (int)TestClassInitialisation.InstantiateForAllMethods,
                nameof(global::TestFramework.Tooling.Execution.Tests.FailInConstructor.Setup), null,
                nameof(global::TestFramework.Tooling.Execution.Tests.FailInConstructor.Cleanup),
                (frm, fdr) =>
                {
                    frm(nameof(global::TestFramework.Tooling.Execution.Tests.FailInDispose.Test), null);
                }
            );

            ForClass(
                typeof(global::TestFramework.Tooling.Execution.Tests.NonFailingTest), (int)TestClassInitialisation.InstantiateForAllMethods,
                nameof(global::TestFramework.Tooling.Execution.Tests.FailInConstructor.Setup), null,
                nameof(global::TestFramework.Tooling.Execution.Tests.FailInConstructor.Cleanup),
                (frm, fdr) =>
                {
                    frm(nameof(global::TestFramework.Tooling.Execution.Tests.NonFailingTest.Test), null);
                }
            );

            ForClass(
                typeof(global::TestFramework.Tooling.Execution.Tests.TestWithMethods), (int)TestClassInitialisation.InstantiateForAllMethods,
                null, null, null,
                (frm, fdr) =>
                {
                    fdr(nameof(global::TestFramework.Tooling.Execution.Tests.TestWithMethods.Test1), null, 0, 1);
                    frm(nameof(global::TestFramework.Tooling.Execution.Tests.TestWithMethods.Test2), null);
                }
            );

            ForClass(
                typeof(global::TestFramework.Tooling.Execution.Tests.TestWithFrameworkExtensions), (int)TestClassInitialisation.InstantiateForAllMethods,
                nameof(global::TestFramework.Tooling.Execution.Tests.TestWithFrameworkExtensions.Setup),
                new object[] {
                    s_cfg_3,
                    CFG_4 // setup will fail
                },
                null,
                (frm, fdr) =>
                {
                    frm(nameof(global::TestFramework.Tooling.Execution.Tests.TestWithFrameworkExtensions.TestDeviceWithSomeFile), new object[] { CFG_1 });
                }
            );


            ForClass(
                typeof(global::TestFramework.Tooling.Execution.Tests.TestWithNewTestMethodsAttributes), (int)TestClassInitialisation.InstantiateForAllMethods,
                null, null, null,
                (frm, fdr) =>
                {
                    fdr(nameof(global::TestFramework.Tooling.Execution.Tests.TestWithNewTestMethodsAttributes.MethodToRunOnRealHardwareWithData), new object[] { CFG_2 }, 0);
                    frm(nameof(global::TestFramework.Tooling.Execution.Tests.TestWithNewTestMethodsAttributes.MethodToRunOnRealHardware), new object[] { CFG_2 });
                }
            );
        }

        private const string CFG_1 = "ConfigValue";
        private const string CFG_2 = "42";
        private static readonly byte[] s_cfg_3 = new byte[] { 42 };
        private const string CFG_4 = "";
    }
}
