// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;

namespace TestFramework.Tooling.UnitTestLauncher.Tests
{
    /// <summary>
    /// This is a program that tests the non-generated code of the
    /// TestFramework.Tooling.UnitTestLauncherGenerator This project
    /// can also be used to code and debug that code.
    ///
    /// The code is included in the TestFramework.Tooling as embedded resource.
    /// It is not tested in the build of TestFramework.Tooling.
    ///
    /// The code below the line depends on the TestFramework.Tooling.Tests.Execution.v3
    /// project. Check and run the test TestFramework_Tooling_UnitTestLauncher_Tests_Asserts
    /// in TestFramework.Tooling.Tests to verify that the data is still correct.
    /// </summary>
    public class Program
    {
        public static void Main()
        {
            Console.WriteLine("========================================");
            Console.WriteLine("UnitTestLauncher test program");
            Console.WriteLine("========================================");

            new nanoFramework.TestFramework.Tools.UnitTestLauncher("NFUnitTest", "***");
        }
    }
}

//===========================================================================================
//
// The code below is normally generated by the UnitTestLauncherGenerator.
//
// The code may need to be adapted if the TestFramework.Tooling.Tests.Execution.v3
// project is updated.
//
// Check and run the test TestFramework_Tooling_UnitTestLauncher_Tests_Asserts
// in TestFramework.Tooling.Tests to verify that the data is still correct.
//

namespace nanoFramework.TestFramework.Tools
{
    public partial class UnitTestLauncher
    {
        partial void RunUnitTests()
        {
            ForClass(
                typeof(global::TestFramework.Tooling.Tests.NFUnitTest.FailInConstructor), 0, true,
                (o) => (o as global::TestFramework.Tooling.Tests.NFUnitTest.FailInConstructor).Setup(),
                (o) => (o as global::TestFramework.Tooling.Tests.NFUnitTest.FailInConstructor).Cleanup(),
                (o, frm, fdr) =>
                {
                    frm((o as global::TestFramework.Tooling.Tests.NFUnitTest.FailInConstructor).Test, 2);
                }
            );

            ForClass(
                typeof(global::TestFramework.Tooling.Tests.NFUnitTest.FailInSetup), 1, true,
                (o) => (o as global::TestFramework.Tooling.Tests.NFUnitTest.FailInSetup).Setup(),
                (o) => (o as global::TestFramework.Tooling.Tests.NFUnitTest.FailInSetup).Cleanup(),
                (o, frm, fdr) =>
                {
                    frm((o as global::TestFramework.Tooling.Tests.NFUnitTest.FailInSetup).Test, 2);
                }
            );

            ForClass(
                typeof(global::TestFramework.Tooling.Tests.NFUnitTest.FailInTest), 2, true,
                (o) => (o as global::TestFramework.Tooling.Tests.NFUnitTest.FailInTest).Setup(),
                (o) => (o as global::TestFramework.Tooling.Tests.NFUnitTest.FailInTest).Cleanup(),
                (o, frm, fdr) =>
                {
                    frm((o as global::TestFramework.Tooling.Tests.NFUnitTest.FailInTest).Test, 2);
                }
            );

            ForClass(
                typeof(global::TestFramework.Tooling.Tests.NFUnitTest.InconclusiveInTest), 3, true,
                (o) => (o as global::TestFramework.Tooling.Tests.NFUnitTest.InconclusiveInTest).Setup(),
                (o) => (o as global::TestFramework.Tooling.Tests.NFUnitTest.InconclusiveInTest).Cleanup(),
                (o, frm, fdr) =>
                {
                    frm((o as global::TestFramework.Tooling.Tests.NFUnitTest.InconclusiveInTest).Test, 2);
                }
            );

            ForClass(
                typeof(global::TestFramework.Tooling.Tests.NFUnitTest.CleanupFailedInTest), 4, true,
                (o) => (o as global::TestFramework.Tooling.Tests.NFUnitTest.CleanupFailedInTest).Setup(),
                (o) => (o as global::TestFramework.Tooling.Tests.NFUnitTest.CleanupFailedInTest).Cleanup(),
                (o, frm, fdr) =>
                {
                    frm((o as global::TestFramework.Tooling.Tests.NFUnitTest.CleanupFailedInTest).Test, 2);
                }
            );

            ForClass(
                typeof(global::TestFramework.Tooling.Tests.NFUnitTest.FailInCleanUp), 5, true,
                (o) => (o as global::TestFramework.Tooling.Tests.NFUnitTest.FailInCleanUp).Setup(),
                (o) => (o as global::TestFramework.Tooling.Tests.NFUnitTest.FailInCleanUp).Cleanup(),
                (o, frm, fdr) =>
                {
                    frm((o as global::TestFramework.Tooling.Tests.NFUnitTest.FailInCleanUp).Test, 2);
                }
            );

            ForClass(
                typeof(global::TestFramework.Tooling.Tests.NFUnitTest.FailInDispose), 6, true,
                (o) => (o as global::TestFramework.Tooling.Tests.NFUnitTest.FailInDispose).Setup(),
                (o) => (o as global::TestFramework.Tooling.Tests.NFUnitTest.FailInDispose).Cleanup(),
                (o, frm, fdr) =>
                {
                    frm((o as global::TestFramework.Tooling.Tests.NFUnitTest.FailInDispose).Test, 2);
                }
            );

            ForClass(
                typeof(global::TestFramework.Tooling.Tests.NFUnitTest.NonFailingTest), 7, true,
                (o) => (o as global::TestFramework.Tooling.Tests.NFUnitTest.NonFailingTest).Setup(),
                (o) => (o as global::TestFramework.Tooling.Tests.NFUnitTest.NonFailingTest).Cleanup(),
                (o, frm, fdr) =>
                {
                    frm((o as global::TestFramework.Tooling.Tests.NFUnitTest.NonFailingTest).Test, 2);
                }
            );

            ForClass(
                typeof(global::TestFramework.Tooling.Tests.NFUnitTest.TestWithMethods), 11, true,
                null, null,
                (o, frm, fdr) =>
                {
                    fdr(nameof(global::TestFramework.Tooling.Tests.NFUnitTest.TestWithMethods.Test1), 0, 0, 1);
                    frm((o as global::TestFramework.Tooling.Tests.NFUnitTest.TestWithMethods).Test2, 1);
                }
            );
        }
    }
}
